# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-19 01:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sotdma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(blank=True, max_length=250, null=True)),
                ('longi', models.CharField(blank=True, max_length=250, null=True)),
                ('lat', models.CharField(blank=True, max_length=250, null=True)),
                ('speed', models.CharField(blank=True, max_length=250, null=True)),
                ('direction', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
